_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
max_comments_per_post:
    value: 750
max_likes_per_post:
    value: 5000
num_posts:
    value: 1000
output_file:
    value: trump_posts_data.csv
username:
    value: realDonaldTrump
